### ISSUE TITLE
s:send_message_to_debugger with :RdbCommand

### ISSUE THREAD

**Issue by fwoeck** [astashov/vim-ruby-debugger#23]
when I call for example
:RdbCommand p User.count

I get an error
E117: unknown function s:send_message_to_debugger

**Comment by astashov** [comment]
Hmm... really strange... Could you open ~/.vim/plugin/ruby_debugger.vim and try to find this function (/send_message_to_debugger). Can you find it?

**Comment by fwoeck** [comment]
Yes, it's there:
function! s:send_message_to_debugger(message) ...

**Comment by astashov** [comment]
Do other features work correctly? (:Rdebugger, next/step/continue commands, set/remove breakpoints...)

**Comment by fwoeck** [comment]
Yes, perfectly! I currently have no idea, how I could help you investigating the problem. Is there any log file place you now I could consult or so? Btw. I do this on a Ubuntu 9.04, this is my .vimrc: git://gist.github.com/123099.git , this is this .vim-tree: git://gist.github.com/123102.git, gvim is vim-gnome (2:7.2.079-1ubuntu5)

**Comment by astashov** [comment]
Well, it is even more strange, because :Rdebugger and others use s:send_message_to_debugger too. Let me suggest some ways:
1.  In command mode, run ':scriptnames' and find SID of ruby_debugger.vim. E.g.:

<pre>
<code>26: /home/anton/.vim/plugin/ruby_debugger.vim</code></pre>
- SID is 26
  Then execute send_message_to_debugger with SID instead of RdbCommand:
  <pre>
  <code>:call <SNR>26_send_message_to_debugger('p User.count')</code></pre>
-  Find string in ~/.vim/plugin/ruby_debugger.vim
  <pre>
  <code>let RubyDebugger.send_command = function ("s:send_message_to_debugger")</code></pre>
  and change it to 
  <pre>
  <code>let RubyDebugger.send_command = function("&lt;SID&gt;send_message_to_debugger")</code></pre>
  Then close and open Vim, run :Rdebugger and try :RdbCommand again.

Tell me if 1 or 2 is worked (or if no one :)). Thanks!

**Comment by fwoeck** [comment]
Hi, the steps 1) and 2) didn't help, _BUT_, I disabled all plugins apart from your's and now it works. So there is probably a conflict with one of these:

```
   deleted:    plugin/CSApprox.vim
   deleted:    plugin/ColorSchemeMenuMaker.vim
   deleted:    plugin/ColorSchemes.vim
   deleted:    plugin/IndexedSearch.vim
   deleted:    plugin/NERDSnippets.vim
   deleted:    plugin/NERD_tree.vim
   deleted:    plugin/allml.vim
   deleted:    plugin/apidock.vim
   deleted:    plugin/bufexplorer.vim
   deleted:    plugin/camelcasemotion.vim
   deleted:    plugin/color_sample_pack.vim
   deleted:    plugin/endwise.vim
   deleted:    plugin/fuzzyfinder.vim
   deleted:    plugin/fuzzyfinder_textmate.vim
   deleted:    plugin/grep.vim
   deleted:    plugin/matchit.vim
   deleted:    plugin/pastie.vim
   deleted:    plugin/rails.vim
   deleted:    plugin/ruby_debugger_test.vim
   deleted:    plugin/surround.vim
   deleted:    plugin/tComment.vim
   deleted:    plugin/taglist.vim
   deleted:    plugin/themes.vim
```

I will re-enable them sequentially and post the results!

**Comment by fwoeck** [comment]
It turned out, that everything works, if I delete ruby_debugger_test.vim from the plugins folder. Im unsure, if I wasn't supposed to install them both?

**Comment by astashov** [comment]
Yeah, you need to remove one of them and leave only ruby_debugger.vim or ruby_debugger_test.vim (second file contains contents of ruby_debugger.vim + unit tests for the plugin). So, if you don't want to run unit tests, you can remove ruby_debugger_test.vim.

Thanks for this research, by the way :) ! I think I'll move out ruby_debugger_test.vim from vim directory.

**Comment by fwoeck** [comment]
Oki, great - thank's a lot for your help!
